/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vues;
import control.EtudiantC;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Etudiant;
public class gestion extends JFrame implements ActionListener{

    /**
     * Creates new form gestion
     */
    public gestion() {
        this.setTitle("Gestion des etudiants");
        this.setSize(600,100);
        this.setLocationRelativeTo(null);
        Container c=getContentPane();
        c.setLayout(new FlowLayout());
        id = new JLabel("Identifiant ");
        id.setBounds(10, 10, 10, 10);
        c.add(id);
        tid= new JTextField(10);
        c.add(tid);
        nom = new JLabel("Nom ");
        c.add(nom);
        tnom= new JTextField(10);
        c.add(tnom);
        prenom = new JLabel("Prénom ");
c.add(prenom);
tprenom= new JTextField(10);
c.add(tprenom);

ajouter = new JButton("Ajouter");
chercher=new JButton("Chercher");
modifier = new JButton("Modifier");
supprimer = new JButton("Supprimer");
c.add(ajouter);
c.add(chercher);
c.add(modifier);
c.add(supprimer);
modifier.addActionListener(this);
ajouter.addActionListener(this);
chercher.addActionListener(this);
supprimer.addActionListener(this);
        
    }
    private JLabel id,nom,prenom;
private JTextField tid,tnom,tprenom;
private JButton ajouter , modifier,supprimer,chercher;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestion().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent a) {
        Object source = a.getSource();
        if(source==ajouter){
        String txtid=tid.getText();
        String txtnom=tnom.getText();
        String txtprenom=tprenom.getText();
        
        
        try{
int id = Integer.parseInt(txtid);
Etudiant e = new Etudiant(id,txtnom, txtprenom) ;
EtudiantC ec= new EtudiantC();
ec.AjouterEtudiant(e);
}catch(Exception ex){
JOptionPane.showMessageDialog(null, "Verifier le champs identifiant doit etre nombre","attention",JOptionPane.ERROR_MESSAGE );

}
}
    if(source == modifier){
String txtid=tid.getText();
try{
int id= Integer.parseInt(txtid);
Etudiant e=new Etudiant(id, tnom.getText(),

tprenom.getText());

EtudiantC ecm= new EtudiantC();
ecm.ModifierEtudiant(e);
    }catch(Exception e){
JOptionPane.showMessageDialog(null, "Verifier le champs identifiant doit etre nombre","attention",JOptionPane.ERROR_MESSAGE );

}
}
    
    if(source==supprimer){
String txtid=tid.getText();
try{
int id= Integer.parseInt(txtid);
Etudiant e=new Etudiant(id);
EtudiantC ecm= new EtudiantC();
ecm.DeleteEtudiant(e);

}catch(Exception e){
JOptionPane.showMessageDialog(null, "Verifier le champs identifiant doit etre nombre","attention",JOptionPane.ERROR_MESSAGE );

}
}
}
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

